version: '3.7'

services:
  backend:
    env_file:
     - .env
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=''  # $SECRET_KEY
    build: ./backend
    command: python3 /code/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: