# Generated by Django 5.0 on 2023-12-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_admins_alter_board_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='boards.board'),
        ),
    ]
