# Generated by Django 5.0 on 2023-12-28 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_stage_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='level',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('targetcompletiondate', models.DateTimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='boards.task')),
            ],
        ),
    ]
