# Generated by Django 5.0 on 2023-12-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_task_level_remove_task_lft_remove_task_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
